config/routes.rb
Rails.application.routes.draw do
  
  resources :companies
  get '/phone_numbers' => 'phone_numbers#index', as: 'phone_numbers'
  post '/phone_numbers' => 'phone_numbers#create'
  get '/phone_numbers/new' => 'phone_numbers#new', as: 'new_phone_number'
  get '/phone_numbers/:id/edit' => 'phone_numbers#edit', as: 'edit_phone_number'
  get '/phone_numbers/:id' => 'phone_numbers#show', as: 'phone_number'
  put '/phone_numbers/:id' => 'phone_numbers#update', as: 'update_phone_number'
  patch '/phone_numbers/:id' => 'phone_numbers#update'
  delete '/phone_numbers/:id' => 'phone_numbers#destroy', as: 'destroy_phone_number'

  get '/email_addresses' => 'email_addresses#index', as: 'email_addresses'
  post '/email_addresses' => 'email_addresses#create'
  get '/email_addresses/new' => 'email_addresses#new', as: 'new_email_address'
  get '/email_addresses/:id/edit' => 'email_addresses#edit', as: 'edit_email_address'
  get '/email_addresses/:id' => 'email_addresses#show', as: 'email_address'
  put '/email_addresses/:id' => 'email_addresses#update', as: 'update_email_address'
  patch '/email_addresses/:id' => 'email_addresses#update'
  delete '/email_addresses/:id' => 'email_addresses#destroy', as: 'destroy_email_address'

	root to: 'people#index'
  resources :people
  
end

app/models/person.rb
class Person < ActiveRecord::Base
	# associations
	has_many :phone_numbers
	has_many :email_addresses

	# validations
	validates :first_name, presence: true
	validates :last_name, presence: true

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th colspan="3">Actions</th>
    </tr>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<p>First Name: <%= @person.first_name %></p>
<p>Last Name: <%= @person.last_name %></p>
<h5>Phone Numbers</h5>
<table>
	<% @person.phone_numbers.each do |phone_number| %>
		<tr>
			<td><%= phone_number.number %></td>
			<td><%= link_to 'Edit', edit_phone_number_path(phone_number) %></td>
			<td><%= link_to 'Delete', destroy_phone_number_path(phone_number), method: :delete %></td>
		</tr>
	<% end %>
</table>
<br />
<h5>Email Addresses</h5>
<table>
	<% @person.email_addresses.each do |email_address| %>
		<tr>
			<td><%= email_address.address %></td>
			<td><%= link_to 'Edit', edit_email_address_path(email_address) %></td>
			<td><%= link_to 'Delete', destroy_email_address_path(email_address), method: :delete %></td>
		</tr>
	<% end %>
</table>

<p></p>
<%= link_to 'Add new Phone Number', new_phone_number_path(person_id: @person.id) %> |
<%= link_to 'Add new Email Address', new_email_address_path(person_id: @person.id) %> |
<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>